# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Folio212 < Formula
  desc "Trading212 portfolio checker"
  homepage "https://github.com/nezdemkovski/folio212"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nezdemkovski/folio212/releases/download/v1.0.0/folio212_1.0.0_darwin_amd64.tar.gz"
      sha256 "e542dce48e8151f62f5cedfb2453d2fc2c3ffb0d2434bcbde2b61ae64fe92f15"

      def install
        bin.install "folio212"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nezdemkovski/folio212/releases/download/v1.0.0/folio212_1.0.0_darwin_arm64.tar.gz"
      sha256 "0be41c7e0af4fb83ce25ccaa4fc143f03153837bd7b915f28bc034273ce4051e"

      def install
        bin.install "folio212"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nezdemkovski/folio212/releases/download/v1.0.0/folio212_1.0.0_linux_amd64.tar.gz"
      sha256 "a5b0bedb86a0e3f78dfb3da30179cf97f941513b7076606738cadf3de45d9800"
      def install
        bin.install "folio212"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nezdemkovski/folio212/releases/download/v1.0.0/folio212_1.0.0_linux_arm64.tar.gz"
      sha256 "e45192977424563b47b9f1071d205e77530184a6212fadff4712501b6d63a0d1"
      def install
        bin.install "folio212"
      end
    end
  end
end
