# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openmarkers < Formula
  desc "OpenMarkers CLI — biomarker and blood test tracker"
  homepage "https://github.com/nezdemkovski/openmarkers-cli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nezdemkovski/openmarkers-cli/releases/download/v0.1.2/openmarkers_0.1.2_darwin_amd64.tar.gz"
      sha256 "7c6dc0f3c8fa72d5b49d3c826d13567652f2bbec5cdc9d7ed29e587fb173a7c1"

      define_method(:install) do
        bin.install "openmarkers"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nezdemkovski/openmarkers-cli/releases/download/v0.1.2/openmarkers_0.1.2_darwin_arm64.tar.gz"
      sha256 "57eb940cce0be92ae1b83b95b29950324bfb0209414ff25fb81f454325c4630c"

      define_method(:install) do
        bin.install "openmarkers"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nezdemkovski/openmarkers-cli/releases/download/v0.1.2/openmarkers_0.1.2_linux_amd64.tar.gz"
      sha256 "f9d13104c117d953c56cc8ec0e10d7adf322e101ec030a67d42de4642965f46d"
      define_method(:install) do
        bin.install "openmarkers"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nezdemkovski/openmarkers-cli/releases/download/v0.1.2/openmarkers_0.1.2_linux_arm64.tar.gz"
      sha256 "d8d3646e8a302b32acb25e2dde8b4dd75aa9b461e63dca6ec0b00c6b4f9146a4"
      define_method(:install) do
        bin.install "openmarkers"
      end
    end
  end
end
