# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Steamdensity < Formula
  desc "Steam discovery CLI - human and AI friendly"
  homepage "https://github.com/nezdemkovski/steamdensity"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nezdemkovski/steamdensity/releases/download/v0.1.0/steamdensity_0.1.0_darwin_amd64.tar.gz"
      sha256 "164a39d2d44897fc4fd8f7195b3bd72e64c6f7f8f0d92dddaeb221775b63c91a"

      def install
        bin.install "steamdensity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nezdemkovski/steamdensity/releases/download/v0.1.0/steamdensity_0.1.0_darwin_arm64.tar.gz"
      sha256 "5cebf171c91eb5f4b4663b9656e2ccd99c2247416fd81da2cc82c25c562c6232"

      def install
        bin.install "steamdensity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nezdemkovski/steamdensity/releases/download/v0.1.0/steamdensity_0.1.0_linux_amd64.tar.gz"
      sha256 "579953c148902b57ac1b9003e6e8fa35de3f1a13ce1a3202f167127b92a7bfd5"
      def install
        bin.install "steamdensity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nezdemkovski/steamdensity/releases/download/v0.1.0/steamdensity_0.1.0_linux_arm64.tar.gz"
      sha256 "2a8dc23b28d180811475ee18452ca039b2191b939db58ada3d2d14a83eca72c1"
      def install
        bin.install "steamdensity"
      end
    end
  end
end
